---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 7.11.2
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  podTemplate:
    metadata:
      labels:
        stack-monitoring.elastic.co/type: beat # to allow autodiscover by metricbeat
      annotations:
        co.elastic.logs/enabled: "true"