---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.11.2
  http:
    service:
      spec:
        type: LoadBalancer #Adds a External IP
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.elasticsearch.collection.enabled: false
    podTemplate:
      metadata:
        labels:
          stack-monitoring.elastic.co/type: es # to allow autodiscover by metricbeat
        annotations:
          co.elastic.logs/enabled: "true"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.11.2
  http:
    service:
      spec:
        type: LoadBalancer #Adds a External IP
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    xpack.monitoring.kibana.collection.enabled: false
    xpack.monitoring.collection.enabled: true
  podTemplate:
    metadata:
      labels:
        stack-monitoring.elastic.co/type: kb # to allow autodiscover by metricbeat
      annotations:
        co.elastic.logs/enabled: "true"
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
spec:
  version: 7.11.2
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  config:
    # https://www.elastic.co/guide/en/apm/server/7.9/monitoring-metricbeat-collection.html
    http.enabled: true
    http.port: 5066
    http.host: 0.0.0.0
    monitoring.enabled: false
  podTemplate:
    metadata:
      labels:
        stack-monitoring.elastic.co/type: beat # to allow autodiscover by metricbeat
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
      - name: apm-server
        ports:
        - containerPort: 5066
          name: monitoring
          protocol: TCP